### ISSUE TITLE
'img_list' is not defined, and more errors when trying text to video

### ISSUE THREAD

**Issue by glennamarshall** [eps696/SDfu#4]
running this..
python src/anima.py -t text.txt -imr _in/pix -m 15drm --frames 200

results in this error,

File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\anima.py", line 128, in <module>
    main()
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\anima.py", line 61, in main
    img_conds = sd.img_cus(a.img_ref, isset(a, 'allref')) # list of [2,1,1024]
  File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\core\sdsetup.py", line 284, in img_cus
    img_conds = [self.img_cu(load_img(im, 224, tensor=False)[0]) for im in img_list(img_path)] # list N of [2,1,..]
NameError: name 'img_list' is not defined. Did you mean: 'file_list'?

but I only got this far by not installing xformers.. when I did install xformers, I got this error,

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.1+cu118 requires torch==2.2.1+cu118, but you have torch 2.2.0 which is incompatible.
torchvision 0.17.1+cu118 requires torch==2.2.1+cu118, but you have torch 2.2.0 which is incompatible.
Successfully installed torch-2.2.0 xformers-0.0.24

(SD) C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu>python src/anima.py -t text.txt -imr _in/pix -m 15drm --frames 200
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.0+cu121 with CUDA 1201 (you have 2.2.0+cpu)
    Python  3.10.11 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\anima.py", line 14, in <module>
    from core.sdsetup import SDfu, device
  File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\core\sdsetup.py", line 19, in <module>
    from .utils import load_img, makemask, isok, isset, progbar, file_list
  File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\core\utils.py", line 16, in <module>
    from .txt2mask import Txt2Mask
  File "C:\Users\ga_ma\Desktop\SDfu\SDfu\SDfu\src\core\txt2mask.py", line 36, in <module>
    from torchvision import transforms
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\torchvision\_meta_registrations.py", line 164, in <module>
    def meta_nms(dets, scores, iou_threshold):
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\torch\library.py", line 440, in inner
    handle = entry.abstract_impl.register(func_to_register, source)
  File "C:\Users\ga_ma\pinokio\bin\miniconda\envs\SD\lib\site-packages\torch\_library\abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist

**Comment by eps696** [comment]
thanks for reporting 
1) first error/bug with `img_list` should be fixed, please check.
2) you should install pytorch with cuda support (e.g. 2.2.0+cu121 as advised by xformers message, but i didn't check that specific version). 
3) it seems there's incompatibility between torch and torchvision versions, please check their correspondence.
just in case, my current setup is cuda 11.8, python 3.9 (3.10 should also work), pytorch 2.0.1+cu118, torchvision 0.15.2+cu118, xformers 0.0.20

**Comment by glennamarshall** [comment]
your instructions worked - thank you!
