### ISSUE TITLE
LatentBlending - No Attribute "use_lcm"

### ISSUE THREAD

**Issue by stavrosdidakis** [eps696/SDfu#7]
I try to run the example: >python src/latwalk.py --img_ref _in/pix --latblend 0.8 --size 1024-576
But I get this error:

```
Traceback (most recent call last):
  File "E:\SDFU\src\latwalk.py", line 200, in <module>
    main()
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\SDFU\src\latwalk.py", line 180, in main
    lb.run_transition(W, H, 1.- a.latblend, a.fstep, reuse = i>0)
  File "E:\SDFU\src\core\latblend.py", line 137, in run_transition
    lats1 = self.compute_latents1() if not reuse or len(self.tree_lats[-1]) != self.steps else self.tree_lats[-1]
  File "E:\SDFU\src\core\latblend.py", line 170, in compute_latents1
    lats1 = self.run_diffusion(cond, pool_c, im_cond, lat_start)
  File "C:\Users\sd163\Anaconda3\envs\SD\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\SDFU\src\core\latblend.py", line 371, in run_diffusion
    if self.sd.use_kdiff or self.isxl or self.use_lcm: # trailing (lcm) or k- schedulers require reset on every generation
AttributeError: 'LatentBlending' object has no attribute 'use_lcm'
```

**Comment by eps696** [comment]
thanks for reporting, fixed
